language: minimal
os:
  - linux
  - osx
  - windows
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis/"
  matrix:
    - JDK="adopt"
    - JDK="adopt@1.8"
    - JDK="adopt-openj9"
#    - JDK="amazon-corretto"
before_install:
  - travis_retry git clone $GRAVIS_REPO $GRAVIS
script:
  - travis_retry source $GRAVIS/install-jdk
  - travis_retry source $GRAVIS/install-maven
  - $GRAVIS/clean-gradle-cache
notifications:
  email:
    if: branch = master
    on_success: never
    on_failure: change
