language: bash
os:
  - linux
  - osx
  - windows
env:
  global:
    - GRAVIS_REPO="git@github.com:DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt"
    - JDK="adopt@1.8"
    - JDK="adopt-openj9"
#    - JDK="amazon-corretto"
before_install:
  - export PATH="$GRAVIS:$PATH"
script:
  - install-jdk
  - install-maven
notifications:
  email:
    if: branch = master
    on_success: never
    on_failure: change
