# UTILITIES

_python_job: &python_job
  stage: python
  script: source $GRAVIS/install-python

_maven_job: &maven_job
  stage: maven
  script: source $GRAVIS/install-maven

if: NOT commit_message =~ /\[\s*SKIP(_|-|\s*)BUILD.*\].*/
language: minimal
os:
  - linux
  - osx
  - windows
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt"
    - JDK="adopt@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.11"
jobs:
  include:
    - <<: *python_job
    - <<: *python_job
      env: PYTHON="3.6.1"
    - <<: *python_job
      os: osx
    - <<: *python_job
      env: PYTHON="3.6.1"
      os: osx
    - <<: *python_job
      os: windows
    - <<: *python_job
      env: PYTHON="3.6.1"
      os: windows
    - <<: *maven_job
    - <<: *maven_job
      env: MAVEN_VERSION="3.6.1"
    - <<: *maven_job
      os: osx
    - <<: *maven_job
      env: MAVEN_VERSION="3.6.1"
      os: osx
    - <<: *maven_job
      os: windows
    - <<: *maven_job
      env: MAVEN_VERSION="3.6.1"
      os: windows
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
script:
  # Never use travis_retry: hides failures. travis_retry is used internally where possible.
  - source $GRAVIS/install-jdk
before_cache:
  - $GRAVIS/clean-gradle-cache
notifications:
  email:
    if: branch = master
    on_success: never
    on_failure: change
