#!/bin/sh

message() {
  cat << EndOfMessage
Release "$1"

Generated automatically by the Gravis-CI auto-tagging script.
EndOfMessage
}

if ! git describe --tags --exact-match HEAD; then
  TENTATIVE_TAG="$(git describe)" || TENTATIVE_TAG="0.1.0-$(git log -n1 --date=format:'%Y-%m-%dT%H%M%S' --format=%cd)"
  git tag "$TENTATIVE_TAG" -m "$(message "$TENTATIVE_TAG")"
fi
echo "Local tag created or already existing: $(git describe --tags --exact-match HEAD)"
