#!/bin/bash
echo 'Searching for the gradle executable and stopping the daemons'
find $HOME -name gradlew -exec {} --stop \; -quit
echo 'Cleanup files triggering unwanted cache refresh'
rm -vfr $HOME/.gradle/caches/*/plugin-resolution
rm -vfr $HOME/.gradle/caches/*/workerMain/
rm -vfr $HOME/.gradle/caches/*/gradle-kotlin-dsl/*/cache/
rm -vfr $HOME/.gradle/caches/*/gradle-kotlin-dsl-accessors/*/cache/
rm -vf $HOME/.gradle/caches/*/fileHashes/*.bin
PATTERNS=(
    '*.class'
    '*.lock'
    'buildSrc.jar'
    'cache.properties'
    'file-access.bin'
    'module-versions.bin'
    'resource-at-url.bin'
    'user-id.txt'
)
for PATTERN in ${PATTERNS[@]}
do
    find "${HOME}/.gradle/caches/" -name "${PATTERN}" -type f -delete -print
done
